name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run code lint
        run: yarn lint

      - name: Run test coverage
        run: yarn test:ci

      - name: Publish on coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}

      - name: Run test cypress
        run: yarn test:cypress:ci

      - name: Deploy on Herkou
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'survey-app-clean-react'
          heroku_email: 'contato@fauzerjunior.com.br'
